name: CircleSquareArchitects
favicon: null
layout_spectrum: 0.04155303863808513
typography_spectrum: 0.3255960519891232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5549608184956014
  lightness: 0.635472173569724
  saturation: 0.05289704306051135
  rhythmicContrast: 0.5806642328388989
purpose: []
