name: CircleSquareArchitects
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3255960519891232
title: Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#b6b6b6'
    - '#595959'
    - '#959595'
    - '#dddddd'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
