name: CircleSquareArchitects
favicon: null
layout_spectrum: 0.25105
typography_spectrum: 0.3255960519891232
title: Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9b9b9'
    - '#000000'
    - '#252525'
    - '#626262'
    - '#e7e7e7'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
