title: Home
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  rhythmicContrast: 0.5
  brandColors:
    - '#111111'
    - '#b6b6b6'
    - '#595959'
    - '#959595'
    - '#dddddd'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: CircleSquareArchitects
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3255960519891232
layout_spectrum: 0.1684588
