name: CircleSquareArchitects
favicon: null
layout_spectrum: 0.04155303863808513
typography_spectrum: 0.3255960519891232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#accad5'
    - '#ffffff'
    - '#e2d6c6'
    - '#4a72a6'
    - '#6193c8'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0.5806642328388989
purpose: []
